### ISSUE TITLE
recent cmessage changes breaks modules

### ISSUE THREAD

**Issue by fred0r** [znc/znc#1040]
i updated my 1.7 znc and ever since the otr (https://github.com/mmilata/znc-otr) and fish (https://github.com/dctrwatson/znc-fish) dont work anymore. i always get the encrypted messages shown.

ZNC 1.7.x-git-271-b402c1e

The older Version was 2-4 weeks older and the modules worked fine.

**Comment by Mikaela** [comment]
You might be interested in http://wiki.znc.in/Branches.

Basically 1.7.x can bring incompatible changes with older versions, 1.6.x only gets bugfixes and is backwards compatible. This issue is lso invalid and you should report issue against those two modules about being incompatible with 1.7.x.

**Comment by jpnurmi** [comment]
The master branch _could_ contain backwards incompatible changes _if_ we were working on a new major version (eg. 2.0.0). Even though we are working on pretty significant internal changes, it looks like we will be able to maintain backwards compatibility and thus, will be able to call it 1.7.0. Sorry for the little turbulence caused by #1000. It's really helpful to have some fearless people running the bleeding edge development version so this kind of issues get caught early. Thanks!
