### ISSUE TITLE
msgs dont show up?

### ISSUE THREAD

**Issue by bl0m1** [znc/znc#1137]
i don't get msgs from anyone, using mirc

**Comment by KindOne-** [comment]
Can you be more specific? Due to the lack of info, I'm just guessing here: in mIRC: Tools -> Options -> Other -> Lock ... Are Chat/Query disabled?

**Comment by bl0m1** [comment]
no everythig is on, if i send a message to someone by open a chat (new tab) whit them i can se what they write, but if i close the chat before i get an answer i cant se it, it woorks perfect if im conecting to irc but when im using znc msgs doesn't show up

**Comment by Mikaela** [comment]
This issue is invalid as it's missing all required information that you were prompted when you opened this issue.

* https://github.com/znc/znc/blob/master/CONTRIBUTING.md

Please add the information requested there or close this issue or it will be closed by someone with access to the issue tracker.

**Comment by Mikaela** [comment]
See also: 
* http://wiki.znc.in/FAQ#I_don.27t_see_buffer_playback_when_attaching_to_ZNC.21
* max buffers option in webadmin.

**Comment by bl0m1** [comment]
i used the ubuntu repo that is linked in znc:s wiki, it was version 1.2?, someone may upgrade that, i run an manual update now and open the issue if the problem still there
