### ISSUE TITLE
ZNC doesn't seem to pass network name to client

### ISSUE THREAD

**Issue by lavacano201014** [znc/znc#1307]
Maybe I'm just an idiot and can't find the relevant config option or something, but I can't get ZNC to properly pass the network provided name to my IRC clients.

Example, with "#testchannel" on EFnet being the example location, connected directly to the network:
![noznc](https://cloud.githubusercontent.com/assets/4407155/17838431/6f19d016-6782-11e6-80a0-54cc01de3211.png)

Same network, same channel, except now through ZNC (with 10 being the first block in the server IP address):
![znc](https://cloud.githubusercontent.com/assets/4407155/17838435/7b39606e-6782-11e6-883d-c44a38e2349c.png)

    09:36 -!- Irssi: Starting query in 10 with *status
    09:36 lavacano ] version
    09:36 *status ] ZNC 1.6.3+deb1 - http://znc.in
    09:36 *status ] IPv6: yes, SSL: yes, DNS: threads, charset: yes

Ubuntu 16.04, no config changes apart from listening on a non-default port

**Comment by teward** [comment]
Currently if ZNC is not connected to a network it doesn't relay a network name, if I remember right

**Comment by Mikaela** [comment]
With good clients you set username to username/network and password to password. With bad clients you say password to username/network:password.

There is no ZNC-side option.

**Comment by lavacano201014** [comment]
You're misinterpreting my problem. The issue is not with connecting to ZNC on a specific network, the issue is with ZNC not telling said clients after connecting "The network is named EFnet, please update your display accordingly". As a result, irssi falls back to the IP address of the server, even though I'm on my networks and channels and chatting just fine.

**Comment by Mikaela** [comment]
Sorry, I misunderstood the issue, teward is right.

**Comment by teward** [comment]
Just to reiterate: ZNC has no functionality to relay the user set network name to the client connection when ZNC itself is not connected to a network (I.e. "empty network name").  It is designed to relay it if a connection is already established to the IRC network because then it knows which name reliably to relay, rather than the network name as user configured.

**Comment by lavacano201014** [comment]
>Currently if ZNC is not connected to a network it doesn't relay a network name, if I remember right

ZNC *is* connected, and the servers are passing the right data along to ZNC, it's just not making it to my actual clients for some reason.

**Comment by RealKindOne** [comment]
Add the network into the client server list. Seems to be the only way for irssi to know what network you are on. Might be other ways but I have no idea.

http://wiki.znc.in/Irssi. 


```
12:57:52 <*status> ZNC 1.7.x-git-633-d0e93c5 - http://znc.in
12:57:52 <*status> IPv6: yes, SSL: yes, DNS: threads, charset: yes, build: autoconf, i18n: no
```

```irssi 0.8.20-g17f4bd2 (20160814 2335)```

**Comment by lavacano201014** [comment]
So this is actually a bug in irssi where it doesn't respect the server-provided network name?

Sorry to bother you then :V

**Comment by psychon** [comment]
Uhm, how does an IRC server provide a network name to the client? Is it some ISUPPORT entry in raw 005? I don't really know. But I do know that ZNC forwards almost everything that it gets from the IRC server to the client.

Also, I'd be interested if "something" happens when you do '/znc jump' so that ZNC reconnects to the IRC server while you are connected (In this case it should really, really, really forward everything that it gets).

**Comment by DarthGandalf** [comment]
@psychon yes, `NETWORK=freenode` in 005
