### ISSUE TITLE
[ZNC 1.6.5] Server encoding settings aren't copied over from the user to a new network [CygWin]

### ISSUE THREAD

**Issue by WildS0ft** [znc/znc#1388]
**OS:** Windows Server 2012 R2
**ZNC version:** ZNC 1.6.5+cygwin1 - http://znc.in
IPv6: yes, SSL: yes, DNS: threads, charset: yes
**CygWin version:** CYGWIN_NT-6.3 Server 2.7.0(0.306/5/3) 2017-02-12 13:18 x86_64 Cygwin

When adding a new network the **Server encoding** settings from the user aren't copied over to the new network properly in the Web-interface.

For example, under the user it's set to:
_Try to parse as UTF-8 and as   **ISO-8859-15**  , send as UTF-8 (recommended)_
But when adding a new network it says:
_Try to parse as UTF-8 and as   **UTF-8**  , send as UTF-8 (recommended)_

**Comment by DarthGandalf** [comment]
There are no server encodings in User. User has client encoding - the one used between IRC client and ZNC.

**Comment by WildS0ft** [comment]
I updated the Title and the comment. I meant the **Client encoding setting** that you can find under **ZNC Behavior**

**Comment by DarthGandalf** [comment]
That doesn't change anything.
There's no client encoding in Network.
Client connects to a user, using client encoding configured in the user; network connects to server using server encoding configured in network. There's no problem having client to use UTF-8 only for all networks, because ZNC handles reencodings per-network internally.

**Comment by WildS0ft** [comment]
My mistake, I didn't read carefully enough. Thought initially they were the same, I see now they are two completely different settings.
