### ISSUE TITLE
Message.GetChan() is always NULL in OnUserTextMessage

### ISSUE THREAD

**Issue by CyberShadow** [znc/znc#1402]
Version: ZNC 1.7.x-git-755-8b48465d

Steps to reproduce:

1. Write a module which overrides `CModule::OnUserTextMessage`
2. Send a message to a channel
3. Observe that `CModule::OnUserTextMessage` is called with a `CMessage` whose `GetChan()` returns `NULL`.

**Comment by DarthGandalf** [comment]
That's because the old non-CMessage version of this callback didn't have CChan. But it makes sense to fill it when possible, yeah; the same for other functions.
This will introduce a caveat, that every module which uses GetChan() needs to check for nullptr. In some cases almost all calls of the callback are not nullptr, so it the module writer can miss such check.
