### ISSUE TITLE
make: No rule to make target '/usr/include/x86_64-linux-gnu/unicode/ucnv.h'

### ISSUE THREAD

**Issue by Zarthus** [znc/znc#1427]
Ambiguous make error, probably means I am missing some sort of dependency.

```bash
[zarthus@starlight ~/dev/znc] $  make                                                  
make: *** No rule to make target '/usr/include/x86_64-linux-gnu/unicode/ucnv.h', needed by 'src/main.o'.  Stop.
```

Seems to be resolved after a `make clean`, but I have no idea what caused it.

**Comment by psychon** [comment]
During compilation, GCC is called in such a way to record which include files it used in a file inside `.depend`. This file is later used by `make` to figure out when it has to rebuild some other file because a header changed. This is mainly meant for modifications to ZNC's own headers, but the file also lists system headers.

In your case, one of these system headers was removed (during an update?). This case is not handled well, as you noticed.

**Comment by Zarthus** [comment]
Yes, the upgrade to Debian 9 was one of the few things that changed (but I had kind of forgotten about) since my last compilation, I figured I'd make a report before the error gets lost in the abyss and clarify on it later.

**Comment by fhazal** [comment]
this happened to me on ubuntu 22.04.3 after updating and upgrading from 22.04.2 it resolved after i use `make clean` recompile back znc.
