### ISSUE TITLE
How to see possible rules for SetRules in log module.

### ISSUE THREAD

**Issue by mDfRg** [znc/znc#1475]
Greetings, I've read documentation about log module (https://wiki.znc.in/Log) and also asked questions on #znc@chat.freenode.net  without luck. I'd like to disable logging of the status changes, so I won't have all these "_***Joins: user001 (IP@address.com)_", "_***Quits:_" and nick changes. I want to have just the conversation written in my log. The wiki doesn't elaborate how to do it. __/msg *log help SetRules__ doesn't list available options. 

There is also this mentioned:

>  Set boolean (added in 1.7)
>  Set one of the following booleans: joins, quits, nickchanges.
>  For example, /msg *log Set quits false to exclude quit messages from the log.

Which makes me think than what I'm looking for isn't available yet?
My ZNC version is ZNC 1.6.5+deb1~bpo8+1 from jessie-backports.

**Comment by teward** [comment]
I think this is quite self-explanatory:

```
SetRules <rules>
    Filter chat rooms which should be logged (all by default).
    Use !#chan or !query to negate and * for wildcards```

This is pretty self-explanatory - you indicate the rules by specifying ***what chat rooms*** you want to not log (or log).  That is, if you are in `#znc` and don't want to log it, you would execute `SetRules !#znc`.

What you ultimately want is `Set boolean` - i.e. `Set quits false` or `Set joins false` or similar.  The problem is, that's only available here in the git build currently - you'd have to compile the software yourself to make this work.

This is, however, *not* something I think we should include in the `help` output for the log module itself - that'd make the output a lot longer than would be 'sane', in my opinion.

**Comment by mDfRg** [comment]
Thank you @teward. I just thought SetRules can be used for more fine-grained customization than yes/no to rooms. But that's okay, it's good to know. Closing issue.
