### ISSUE TITLE
Makefile error

### ISSUE THREAD

**Issue by Tweetvito** [znc/znc#1517]
on 1.7.0-rc makefile have error about : gtest and gmock
there are no rules to generate

**Comment by DarthGandalf** [comment]
Paste full logs, what exact commands you run, system info, etc

2018-04-22 10:33 GMT+01:00 Tweetvito <notifications@github.com>:

**Comment by Tweetvito** [comment]
i try to create deb package with command : debuild -us -uc -b
system : debian 8 and 9
----------------------------------------------------------------
Building core object Message...
Building core object Translation...
Linking znc...

 ZNC was successfully compiled.
 Use 'make install' to install ZNC to '/usr'.
make[1]: uscita dalla directory "/home/vito/Scaricati/znc-1.7.0-rc1"
   dh_auto_test
	make -j1 test VERBOSE=1
make[1]: ingresso nella directory "/home/vito/Scaricati/znc-1.7.0-rc1"
make[1]: ***  Nessuna regola per generare l'obiettivo "third_party/googletest/googletest/src/gtest-all.cc", necessario per "test/gtest-all.o".  Arresto.
make[1]: uscita dalla directory "/home/vito/Scaricati/znc-1.7.0-rc1"
dh_auto_test: make -j1 test VERBOSE=1 returned exit code 2
debian/rules:18: set di istruzioni per l'obiettivo "build" non riuscito
make: *** [build] Errore 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
debuild: fatal error at line 1116:
dpkg-buildpackage -rfakeroot -us -uc -b failed

**Comment by DarthGandalf** [comment]
Tarballs don't provide GTest and GMock, which are needed to run `make test`. If you're building from git checkout, they are available as git submodule, so by default `make test` expects to find those files in `third_party/googletest/`
You can also install gtest in some other way, e.g. via googletest Debian package, and call `./configure --with-gtest=/usr/src/googletest/googletest --with-gmock=/usr/src/googletest/googlemock` or `env GTEST_ROOT=/usr/src/googletest/googletest GMOCK_ROOT=/usr/src/googletest/googlemock cmake ...`
Note that in CMake build you can call the same test suite with `make unittest` instead of `make test`.

**Comment by Tweetvito** [comment]
Problem solved 
first solution : ./configure --with-gtest=/usr/src/googletest/googletest --with-gmock=/usr/src/googletest/googlemock
second solution : change the lines in Makefile 
GTEST_DIR := $(srcdir)/third_party/googletest/googletest
to
GTEST_DIR := /usr/src/googletest/googletest
and 
GMOCK_DIR := $(srcdir)/third_party/googletest/googlemock
to
GMOCK_DIR := /usr/src/googletest/googlemock

result ...
dpkg-deb: building package 'znc-dbgsym' in '../znc-dbgsym_1.7.0-rc1-1_amd64.deb'.
dpkg-deb: building package 'znc' in '../znc_1.7.0-rc1-1_amd64.deb'.

Thank You all
