### ISSUE TITLE
Duplicate OnChanMsg calls in python modules

### ISSUE THREAD

**Issue by linuxdaemon** [znc/znc#1588]
The title says it all. I have observed that the `OnChanMsg` method on a python module is being called twice per message. It seems that `modpython` calls `OnChanMsg` in its override of `OnChanTextMessage` https://github.com/znc/znc/blob/d58563a88014610b0fd1112e74f7e127d55774b4/modules/modpython/znc.py#L640 but so does the core https://github.com/znc/znc/blob/d58563a88014610b0fd1112e74f7e127d55774b4/src/Modules.cpp#L947

**Comment by DarthGandalf** [comment]
Your python module is broken, and doesn't follow the contract. My telepathy skills tell me that you didn't return the `EModRet` value from your `OnChanMsg`, but next time please pastebin the module, so that I don't have to guess.

**Comment by linuxdaemon** [comment]
The module in question is https://github.com/snoonetIRC/znc-modules/blob/master/push.py and you were correct. The original author of the module neglected to return `znc.CONTINUE` from some of the callbacks that have an `EModRet` return value. Sorry to bother you.

**Comment by A-UNDERSCORE-D** [comment]
>Your python module is broken, and doesn't follow the contract. My telepathy skills tell me that you didn't return the EModRet value from your OnChanMsg, but next time please pastebin the module, so that I don't have to guess.

According to the [modpython documentation](https://wiki.znc.in/Modpython), functions that return None should have a 'reasonable default' substituted (`If a callback returns None, a reasonable default is substituted. If a callback raises an exception, the default value is assumed too. Note: You should return something explicitly anyway (PEP 20), also such default behavior WILL be changed in some future version.`)

The function being called twice does not exactly fit under `reasonable default`, and while this is now a deprecated function, it should still maintain past functionality. Or the docs should be changed to indicate that a return is **required** rather than simply suggested. Especially given that this was not always the case.

**Comment by DarthGandalf** [comment]
> also such default behavior WILL be changed in some future version

It was changed in 1.7, alright :) But docs should be updated to reflect this, sure.

**Comment by DarthGandalf** [comment]
This started as an implementation detail, followed by the description of current behavior, *with no guarantees* that this behavior will persist, even vice versa, it was suggested that it will *not* persist.

**Comment by A-UNDERSCORE-D** [comment]
Agreed, on both counts
