### ISSUE TITLE
Remove partyline

### ISSUE THREAD

**Issue by Zarthus** [znc/znc#1632]
I think most users who enable partyline are misguidingly thinking it's 100% functional, and supporting them is a bit annoying. Clearly nobody has cared to fix it since 1.0 so it's on nobodies priority list. I'd say we should remove it entirely and refer to it as a third party module.

**Comment by teward** [comment]
While I don't disagree, the source code would need to move somewhere else for it to be considered "third party".  If we want to consider it as a third party module, it needs to be accessible.

I would be more in favor of just removing it entirely, rather than calling it a "third party module".  Anyone who wants it can dig around in the source code for older versions of the released tarballs to refer to the source code for the module and 'add it' if they want it.

**Comment by Zarthus** [comment]
yep, if source code edits beyond that are needed  it's just extra unnecessary maintenance I don't think we should want.
