### ISSUE TITLE
1.8.1 upgrade breaks SSL compatibility with some servers

### ISSUE THREAD

**Issue by dcorbe** [znc/znc#1743]
I'm trying to connect to a network I had configured perfectly fine in 1.6 and I now get the following error:

Disconnected from IRC (error:1408F10B:SSL routines:ssl3_get_record:wrong version number). Reconnecting...

How do I fix this?  It's a vague error message.

**Comment by psychon** [comment]
How did you compile ZNC? Did you do it yourself? Did you do an OS upgrade? Some OSs disable some versions of the TLS protocol in OpenSSL.

> How do I fix this? It's a vague error message.

The error is something like "the other end tried to talk TLS 1.0, but I do not want to talk that". I am not entirely sure and I also find OpenSSL's error messages cryptic.

You could try connecting on the command line with something like `openssl s_client -connect irc.freenode.org:6697`. This says something like `New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384` somewhere in the middle (after the certificates). So, this is TLS 1.3. If your IRC server has something else here, my guess about what the issue is could be right.

**Comment by psychon** [comment]
What happened? Did you fix your problem? What was the solution?

**Comment by farynaio** [comment]
I have the same problem, reported in https://github.com/znc/znc/issues/1781.
