### ISSUE TITLE
Retire the awaynick module [$20 awarded]

### ISSUE THREAD

**Issue by jpnurmi** [znc/znc#661]
Proposal:
- Write a wiki page _politely_ explaining why away nicks are bad. Collect ideas from:
  - http://bisqwit.iki.fi/jutut/away.html
  - http://sackheads.org/~bnaylor/spew/away_msgs.html
- Make the current **awaynick** module available somewhere
  - Rename it to **awaynicksarebad** or something, so it won't collide later
  - Reference from the [awaynick](http://wiki.znc.in/Awaynick) module wiki page
- Cripple the awaynick module so that it still loads, but does nothing besides throwing warnings
  - IRC: on load & module command, warn that the module is retired and give the wiki link
  - Terminal: just in case someone runs ZNC with debug output, print a bold red warning on startup. The return message from OnLoad is not well visible, so either fix that or use CUtils::PutStatus(false, "...") directly?
##

**Comment by gdude2002** [comment]
Just out of interest (and sorry for necroing), but why was this Bountysource'd?

Not trying to stir the pot or anything, but it looks like something that would have been fairly simple for the ZNC team to do themselves, once a consensus had been reached by the community.

**Comment by jpnurmi** [comment]
Anyone is free to set bounty on any issue they would like to see resolved. It doesn't need to have anything to do with the complexity of an issue. It's also a way to voice your opinion.

**Comment by rakiru** [comment]
Why the rename? Why can't it just be removed from core? This causes unnecessary hassle for people who want to use it (and those people are already going out of their way to get it, so it's not stopping anyone).

**Comment by Mikaela** [comment]
>  (and sorry for necroing), 

While jpnurmi already answered I would like to add that I don't think there is necroing with issue trackers as the bug can always resurface or there are new ideas to it.

> Why the rename? Why can't it just be removed from core? This causes (seemingly unnecessary) hassle for people who want to use it (and those people are already going out of their way to get it, so it's not stopping anyone).

I assume that by rename you mean that it loads the simple_away module which has there always. It cannot be removed entirely, because that would make ZNC not start for the users who had it loaded previously after upgrading.

From what I have understood the module will be loaded eventually.

See also:

* http://wiki.znc.in/awaynick

**Comment by gdude2002** [comment]
> Anyone is free to set bounty on any issue they would like to see resolved. It doesn't need to have anything to do with the complexity of an issue. It's also a way to voice your opinion.

It seems kind of a bad way to do so when the community is so clearly divided, though. I mean, I get that your opinion was that `awaynick` should be removed, which is fine, but it seems kind of like one is putting a spanner in the works by throwing money at it instead of allowing the community to resolve its opinions itself, if you see what I mean.

> I assume that by rename you mean that it loads the simple_away module which has there always. It cannot be removed entirely, because that would make ZNC not start for the users who had it loaded previously after upgrading.

I think he's referring to the fact that in the ZNC core, attempting to load `awaynick` automatically loads `simple_away` instead - if users want to use a module with that name, they have to rename it. That seems kind of unnecessary, no? IMHO it would be better to replace it with an actual module named `awaynick` that gives a warning or itself loads `simple_away` - [which is exactly what there is](https://github.com/znc/znc/blob/master/modules/awaynick.cpp).

**Comment by rakiru** [comment]
>I think he's referring to the fact that in the ZNC core, attempting to load awaynick automatically loads simple_away instead - if users want to use a module with that name, they have to rename it.

Yes, this. If I upgrade and put the old awaynick module in there, as far as I can tell, it won't be loaded, since the "awaynick" in my configs is going to just load simple_away instead.

**Comment by jpnurmi** [comment]
As far as I can tell, simple_away is loaded only if awaynick fails to load. Your self-built ~/.znc/modules/awaynick.so takes precedence over the installation dir.

**Comment by Mikaela** [comment]
> MHO it would be better to replace it with an actual module named awaynick that gives a warning or itself loads simple_away - which is exactly what there is.

You lost me :)

**Comment by rakiru** [comment]
@jpnurmi Yeah, I missed that first time around but realised 15 minutes ago. Thanks though.
