### ISSUE TITLE
sasl: show which mechanism succeeds

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#770]
Currently \*sasl only tells failing mechanisms, but if I have multiple mechanisms, I only see the failing ones.

Examples on how I think it should work:

* Some modern network with mechanisms EXTERNAL ECDSA-NIST256P-CHALLENGE PLAIN :

> EXTERNAL succeeded.
> mechanisms that weren't attempted: ECDSA-NIST256P-CHALLENGE PLAIN 

* maybe freenode:

> EXTERNAL failed.
> ECDSA-NIST256P-CHALLENGE succeeded.
> mechanisms that weren't attempted: PLAIN 

* and some third older network could say:

> EXTERNAL failed.
> ECDSA-NIST256P-CHALLENGE failed.

    * and as this network had only PLAIN left and it succeeded, it doesn't need any mention.

If I had configured only PLAIN on all networks and it succeeded there, no notice would be given which is the same as with current behaviour.

* * * * *

*I acted that https://github.com/znc/znc/issues/746 was already done so the list could be more often used.*

**Comment by Mikaela** [comment]
This would be more important since https://github.com/znc/znc/commit/02ba375966a5713ff316a3e122fd1f57f575ebe6 now that all SASL mechanisms are enabled by default as some users are confused by error about EXTERNAL failing without any kind of notice on PLAIN succeeding instead.

**Comment by GLolol** [comment]
Frankly... I'd much prefer the SASL mechanism announcements be compacted into one line (like https://github.com/GLolol/znc/commit/9764bc5b41 though preferably in a notice instead of PRIVMSG). 
:+1: for putting all this mechanism stuff into a `verbose` option of some sort. Unless you're debugging, it doesn't really matter which mechanisms you have defined as long as one of them works.
