### ISSUE TITLE
Makefile:167: recipe for target 'third_party/Csocket/Csocket.h' failed

### ISSUE THREAD

**Issue by schwickster** [znc/znc#806]
Seems the following code is missing some double quotes on line 167 in Makefile.in.

@echo It looks like git submodules are not initialized. Run: git submodule update --init --recursive

**Comment by DarthGandalf** [comment]
This line in Makefile.in is fine. It shows the message, as it's supposed to:
```
It looks like git submodules are not initialized. Run: git submodule update --init --recursive
```

If you would use git directly, it's the message for you, it explains what user needs to do in order to update git submodules.

But you're installing not directly from git, but via https://aur.archlinux.org/packages/znc-git/ , so it's https://aur.archlinux.org/packages/znc-git/ 's job to update git submodules.
So archlinux package for znc-git needs to be fixed.

**Comment by DarthGandalf** [comment]
@gtmanfred Please look at it

**Comment by gtmanfred** [comment]
I will take a look tonight after work.

**Comment by gtmanfred** [comment]
Updated
